### ISSUE TITLE
Problem With Code

### ISSUE THREAD

**Issue by Nasvera** [kameranis/HashCode-2017#1]
Hy Karmerains, nic work , i got ur code for de pizza solution but when running it to fine the out put so i could modify it, it give an error , "Traceback (most recent call last):
  File "/nas/Documents/Hash Code 2017/hashCode-Solution/hashcode-2017-python2/pizza/pizza.py", line 88, in <module>
    if __name__ == '__main__': main()
  File "/nas/Documents/Hash Code 2017/hashCode-Solution/hashcode-2017-python2/pizza/pizza.py", line 70, in main
    p, l, h = parse()
  File "/nas/Documents/Hash Code 2017/hashCode-Solution/hashcode-2017-python2/pizza/pizza.py", line 11, in parse
    r, _, l, h = map(int, input().split())
  File "<string>", line 1
    6 7 1 5
      ^
SyntaxError: invalid syntax "

is't that am not running it well?
what is the problem? (i also code in python , c# and java).

**Comment by kameranis** [comment]
Good morning Nasvera,

This repo was supposed to be private and it was an oversight of us that we left it public. The problem is probably that you have wrong input. However I would please you to delete our code, as we are not supposed to share.

Konstantinos Ameranis
